### ISSUE TITLE
Courses | Correct "Open Paper"

### ISSUE THREAD

**Issue by SabaBaig** [open-learning-exchange/BeLL-Apps#289]
- Currently, when a document is uploaded under "Upload Paper" and user tries to open that document then it  opens a json document in browser. Which is an error. It should be like **Download Paper** instead of **Open Paper**.
- Secondly, when someone clicks on **Download Paper**, it should be downloaded automatically to that user's machine.

**Comment by SabaBaig** [comment]
Way to open a paper
![issue289](https://cloud.githubusercontent.com/assets/13994879/15778098/82806240-29ad-11e6-8503-7d7c81cf92a5.png)

**Comment by SabaBaig** [comment]
In order, to solve this issue, the per-requisite of this issue should be solved first.
https://github.com/open-learning-exchange/BeLL-Apps/issues/299

**Comment by SabaBaig** [comment]
Please also handle the "No attachment" error properly (i.e it should not say no attachment on just file extension error) and make sure that the document is also saved into the database.

**Comment by umarWaris** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/9655887b005f1fb11d82ed66fc40efe82089ec5e
https://github.com/open-learning-exchange/BeLL-Apps/commit/d8161d4b780136b98a092752a0eceaf70ede8902

**Comment by EmilyLarkin** [comment]
@umarWaris @SabaBaig so this works in the sense that there is no .json document popping up, however the button still does not say "Download Paper", instead it merely says where the paper for step #X. I don't want to close this issue yet as this needs to be corrected in the badges/"Progress" improvement in other issues.

**Comment by umarWaris** [comment]
I changed the button text 
![capture](https://cloud.githubusercontent.com/assets/17467658/17013310/0d72d00a-4f37-11e6-9f31-f75b1287e2c3.PNG)

**Comment by umarWaris** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/bf98d38710704fced4e0cc08d06a7daf43dd61a3

**Comment by EmilyLarkin** [comment]
To clarify, which branch should I test on? I was slightly confused about the courses label as I am unsure if this development is on dev. @umarWaris please let me know and I will review it.
